-- Fix all country capitals with real data
UPDATE countries SET capital = 'Kabul' WHERE id = 'afghanistan';
UPDATE countries SET capital = 'Tirana' WHERE id = 'albania';
UPDATE countries SET capital = 'Algiers' WHERE id = 'algeria';
UPDATE countries SET capital = 'Andorra la Vella' WHERE id = 'andorra';
UPDATE countries SET capital = 'Luanda' WHERE id = 'angola';
UPDATE countries SET capital = 'St. John''s' WHERE id = 'antigua-barbuda';
UPDATE countries SET capital = 'Buenos Aires' WHERE id = 'argentina';
UPDATE countries SET capital = 'Yerevan' WHERE id = 'armenia';
UPDATE countries SET capital = 'Canberra' WHERE id = 'australia';
UPDATE countries SET capital = 'Vienna' WHERE id = 'austria';
UPDATE countries SET capital = 'Baku' WHERE id = 'azerbaijan';
UPDATE countries SET capital = 'Nassau' WHERE id = 'bahamas';
UPDATE countries SET capital = 'Manama' WHERE id = 'bahrain';
UPDATE countries SET capital = 'Dhaka' WHERE id = 'bangladesh';
UPDATE countries SET capital = 'Bridgetown' WHERE id = 'barbados';
UPDATE countries SET capital = 'Minsk' WHERE id = 'belarus';
UPDATE countries SET capital = 'Brussels' WHERE id = 'belgium';
UPDATE countries SET capital = 'Belmopan' WHERE id = 'belize';
UPDATE countries SET capital = 'Porto-Novo' WHERE id = 'benin';
UPDATE countries SET capital = 'Thimphu' WHERE id = 'bhutan';
UPDATE countries SET capital = 'Sucre' WHERE id = 'bolivia';
UPDATE countries SET capital = 'Sarajevo' WHERE id = 'bosnia-herzegovina';
UPDATE countries SET capital = 'Gaborone' WHERE id = 'botswana';
UPDATE countries SET capital = 'Brasília' WHERE id = 'brazil';
UPDATE countries SET capital = 'Bandar Seri Begawan' WHERE id = 'brunei';
UPDATE countries SET capital = 'Sofia' WHERE id = 'bulgaria';
UPDATE countries SET capital = 'Ouagadougou' WHERE id = 'burkina-faso';
UPDATE countries SET capital = 'Gitega' WHERE id = 'burundi';
UPDATE countries SET capital = 'Praia' WHERE id = 'cabo-verde';
UPDATE countries SET capital = 'Phnom Penh' WHERE id = 'cambodia';
UPDATE countries SET capital = 'Yaoundé' WHERE id = 'cameroon';
UPDATE countries SET capital = 'Ottawa' WHERE id = 'canada';
UPDATE countries SET capital = 'Bangui' WHERE id = 'central-african-republic';
UPDATE countries SET capital = 'N''Djamena' WHERE id = 'chad';
UPDATE countries SET capital = 'Santiago' WHERE id = 'chile';
UPDATE countries SET capital = 'Beijing' WHERE id = 'china';
UPDATE countries SET capital = 'Bogotá' WHERE id = 'colombia';
UPDATE countries SET capital = 'Moroni' WHERE id = 'comoros';
UPDATE countries SET capital = 'Brazzaville' WHERE id = 'congo-brazzaville';
UPDATE countries SET capital = 'Kinshasa' WHERE id = 'congo-kinshasa';
UPDATE countries SET capital = 'San José' WHERE id = 'costa-rica';
UPDATE countries SET capital = 'Zagreb' WHERE id = 'croatia';
UPDATE countries SET capital = 'Havana' WHERE id = 'cuba';
UPDATE countries SET capital = 'Nicosia' WHERE id = 'cyprus';
UPDATE countries SET capital = 'Prague' WHERE id = 'czech-republic';
UPDATE countries SET capital = 'Copenhagen' WHERE id = 'denmark';
UPDATE countries SET capital = 'Djibouti City' WHERE id = 'djibouti';
UPDATE countries SET capital = 'Roseau' WHERE id = 'dominica';
UPDATE countries SET capital = 'Santo Domingo' WHERE id = 'dominican-republic';
UPDATE countries SET capital = 'Quito' WHERE id = 'ecuador';
UPDATE countries SET capital = 'Cairo' WHERE id = 'egypt';
UPDATE countries SET capital = 'San Salvador' WHERE id = 'el-salvador';
UPDATE countries SET capital = 'Malabo' WHERE id = 'equatorial-guinea';
UPDATE countries SET capital = 'Asmara' WHERE id = 'eritrea';
UPDATE countries SET capital = 'Tallinn' WHERE id = 'estonia';
UPDATE countries SET capital = 'Mbabane' WHERE id = 'eswatini';
UPDATE countries SET capital = 'Addis Ababa' WHERE id = 'ethiopia';
UPDATE countries SET capital = 'Suva' WHERE id = 'fiji';
UPDATE countries SET capital = 'Helsinki' WHERE id = 'finland';
UPDATE countries SET capital = 'Paris' WHERE id = 'france';
UPDATE countries SET capital = 'Libreville' WHERE id = 'gabon';
UPDATE countries SET capital = 'Banjul' WHERE id = 'gambia';
UPDATE countries SET capital = 'Tbilisi' WHERE id = 'georgia';
UPDATE countries SET capital = 'Berlin' WHERE id = 'germany';
UPDATE countries SET capital = 'Accra' WHERE id = 'ghana';
UPDATE countries SET capital = 'Athens' WHERE id = 'greece';
UPDATE countries SET capital = 'St. George''s' WHERE id = 'grenada';
UPDATE countries SET capital = 'Guatemala City' WHERE id = 'guatemala';
UPDATE countries SET capital = 'Conakry' WHERE id = 'guinea';
UPDATE countries SET capital = 'Bissau' WHERE id = 'guinea-bissau';
UPDATE countries SET capital = 'Georgetown' WHERE id = 'guyana';
UPDATE countries SET capital = 'Port-au-Prince' WHERE id = 'haiti';
UPDATE countries SET capital = 'Tegucigalpa' WHERE id = 'honduras';
UPDATE countries SET capital = 'Budapest' WHERE id = 'hungary';
UPDATE countries SET capital = 'Reykjavík' WHERE id = 'iceland';
UPDATE countries SET capital = 'New Delhi' WHERE id = 'india';
UPDATE countries SET capital = 'Jakarta' WHERE id = 'indonesia';
UPDATE countries SET capital = 'Tehran' WHERE id = 'iran';
UPDATE countries SET capital = 'Baghdad' WHERE id = 'iraq';
UPDATE countries SET capital = 'Dublin' WHERE id = 'ireland';
UPDATE countries SET capital = 'Jerusalem' WHERE id = 'israel';
UPDATE countries SET capital = 'Rome' WHERE id = 'italy';
UPDATE countries SET capital = 'Yamoussoukro' WHERE id = 'ivory-coast';
UPDATE countries SET capital = 'Kingston' WHERE id = 'jamaica';
UPDATE countries SET capital = 'Tokyo' WHERE id = 'japan';
UPDATE countries SET capital = 'Amman' WHERE id = 'jordan';
UPDATE countries SET capital = 'Astana' WHERE id = 'kazakhstan';
UPDATE countries SET capital = 'Nairobi' WHERE id = 'kenya';
UPDATE countries SET capital = 'Tarawa' WHERE id = 'kiribati';
UPDATE countries SET capital = 'Pristina' WHERE id = 'kosovo';
UPDATE countries SET capital = 'Kuwait City' WHERE id = 'kuwait';
UPDATE countries SET capital = 'Bishkek' WHERE id = 'kyrgyzstan';
UPDATE countries SET capital = 'Vientiane' WHERE id = 'laos';
UPDATE countries SET capital = 'Riga' WHERE id = 'latvia';
UPDATE countries SET capital = 'Beirut' WHERE id = 'lebanon';
UPDATE countries SET capital = 'Maseru' WHERE id = 'lesotho';
UPDATE countries SET capital = 'Monrovia' WHERE id = 'liberia';
UPDATE countries SET capital = 'Tripoli' WHERE id = 'libya';
UPDATE countries SET capital = 'Vaduz' WHERE id = 'liechtenstein';
UPDATE countries SET capital = 'Vilnius' WHERE id = 'lithuania';
UPDATE countries SET capital = 'Luxembourg City' WHERE id = 'luxembourg';
UPDATE countries SET capital = 'Antananarivo' WHERE id = 'madagascar';
UPDATE countries SET capital = 'Lilongwe' WHERE id = 'malawi';
UPDATE countries SET capital = 'Kuala Lumpur' WHERE id = 'malaysia';
UPDATE countries SET capital = 'Malé' WHERE id = 'maldives';
UPDATE countries SET capital = 'Bamako' WHERE id = 'mali';
UPDATE countries SET capital = 'Valletta' WHERE id = 'malta';
UPDATE countries SET capital = 'Majuro' WHERE id = 'marshall-islands';
UPDATE countries SET capital = 'Nouakchott' WHERE id = 'mauritania';
UPDATE countries SET capital = 'Port Louis' WHERE id = 'mauritius';
UPDATE countries SET capital = 'Mexico City' WHERE id = 'mexico';
UPDATE countries SET capital = 'Palikir' WHERE id = 'micronesia';
UPDATE countries SET capital = 'Chișinău' WHERE id = 'moldova';
UPDATE countries SET capital = 'Monaco' WHERE id = 'monaco';
UPDATE countries SET capital = 'Ulaanbaatar' WHERE id = 'mongolia';
UPDATE countries SET capital = 'Podgorica' WHERE id = 'montenegro';
UPDATE countries SET capital = 'Rabat' WHERE id = 'morocco';
UPDATE countries SET capital = 'Maputo' WHERE id = 'mozambique';
UPDATE countries SET capital = 'Naypyidaw' WHERE id = 'myanmar';
UPDATE countries SET capital = 'Windhoek' WHERE id = 'namibia';
UPDATE countries SET capital = 'Yaren' WHERE id = 'nauru';
UPDATE countries SET capital = 'Kathmandu' WHERE id = 'nepal';
UPDATE countries SET capital = 'Amsterdam' WHERE id = 'netherlands';
UPDATE countries SET capital = 'Wellington' WHERE id = 'new-zealand';
UPDATE countries SET capital = 'Managua' WHERE id = 'nicaragua';
UPDATE countries SET capital = 'Niamey' WHERE id = 'niger';
UPDATE countries SET capital = 'Abuja' WHERE id = 'nigeria';
UPDATE countries SET capital = 'Pyongyang' WHERE id = 'north-korea';
UPDATE countries SET capital = 'Skopje' WHERE id = 'north-macedonia';
UPDATE countries SET capital = 'Oslo' WHERE id = 'norway';
UPDATE countries SET capital = 'Muscat' WHERE id = 'oman';
UPDATE countries SET capital = 'Islamabad' WHERE id = 'pakistan';
UPDATE countries SET capital = 'Ngerulmud' WHERE id = 'palau';
UPDATE countries SET capital = 'Ramallah' WHERE id = 'palestine';
UPDATE countries SET capital = 'Panama City' WHERE id = 'panama';
UPDATE countries SET capital = 'Port Moresby' WHERE id = 'papua-new-guinea';
UPDATE countries SET capital = 'Asunción' WHERE id = 'paraguay';
UPDATE countries SET capital = 'Lima' WHERE id = 'peru';
UPDATE countries SET capital = 'Manila' WHERE id = 'philippines';
UPDATE countries SET capital = 'Warsaw' WHERE id = 'poland';
UPDATE countries SET capital = 'Lisbon' WHERE id = 'portugal';
UPDATE countries SET capital = 'Doha' WHERE id = 'qatar';
UPDATE countries SET capital = 'Bucharest' WHERE id = 'romania';
UPDATE countries SET capital = 'Moscow' WHERE id = 'russia';
UPDATE countries SET capital = 'Kigali' WHERE id = 'rwanda';
UPDATE countries SET capital = 'Basseterre' WHERE id = 'saint-kitts-nevis';
UPDATE countries SET capital = 'Castries' WHERE id = 'saint-lucia';
UPDATE countries SET capital = 'Kingstown' WHERE id = 'saint-vincent-grenadines';
UPDATE countries SET capital = 'Apia' WHERE id = 'samoa';
UPDATE countries SET capital = 'San Marino' WHERE id = 'san-marino';
UPDATE countries SET capital = 'São Tomé' WHERE id = 'sao-tome-principe';
UPDATE countries SET capital = 'Riyadh' WHERE id = 'saudi-arabia';
UPDATE countries SET capital = 'Dakar' WHERE id = 'senegal';
UPDATE countries SET capital = 'Belgrade' WHERE id = 'serbia';
UPDATE countries SET capital = 'Victoria' WHERE id = 'seychelles';
UPDATE countries SET capital = 'Freetown' WHERE id = 'sierra-leone';
UPDATE countries SET capital = 'Singapore' WHERE id = 'singapore';
UPDATE countries SET capital = 'Bratislava' WHERE id = 'slovakia';
UPDATE countries SET capital = 'Ljubljana' WHERE id = 'slovenia';
UPDATE countries SET capital = 'Honiara' WHERE id = 'solomon-islands';
UPDATE countries SET capital = 'Mogadishu' WHERE id = 'somalia';
UPDATE countries SET capital = 'Pretoria' WHERE id = 'south-africa';
UPDATE countries SET capital = 'Seoul' WHERE id = 'south-korea';
UPDATE countries SET capital = 'Juba' WHERE id = 'south-sudan';
UPDATE countries SET capital = 'Madrid' WHERE id = 'spain';
UPDATE countries SET capital = 'Sri Jayawardenepura Kotte' WHERE id = 'sri-lanka';
UPDATE countries SET capital = 'Khartoum' WHERE id = 'sudan';
UPDATE countries SET capital = 'Paramaribo' WHERE id = 'suriname';
UPDATE countries SET capital = 'Stockholm' WHERE id = 'sweden';
UPDATE countries SET capital = 'Bern' WHERE id = 'switzerland';
UPDATE countries SET capital = 'Damascus' WHERE id = 'syria';
UPDATE countries SET capital = 'Dushanbe' WHERE id = 'tajikistan';
UPDATE countries SET capital = 'Dodoma' WHERE id = 'tanzania';
UPDATE countries SET capital = 'Bangkok' WHERE id = 'thailand';
UPDATE countries SET capital = 'Dili' WHERE id = 'timor-leste';
UPDATE countries SET capital = 'Lomé' WHERE id = 'togo';
UPDATE countries SET capital = 'Nukuʻalofa' WHERE id = 'tonga';
UPDATE countries SET capital = 'Port of Spain' WHERE id = 'trinidad-tobago';
UPDATE countries SET capital = 'Tunis' WHERE id = 'tunisia';
UPDATE countries SET capital = 'Ankara' WHERE id = 'turkey';
UPDATE countries SET capital = 'Ashgabat' WHERE id = 'turkmenistan';
UPDATE countries SET capital = 'Funafuti' WHERE id = 'tuvalu';
UPDATE countries SET capital = 'Kampala' WHERE id = 'uganda';
UPDATE countries SET capital = 'Kyiv' WHERE id = 'ukraine';
UPDATE countries SET capital = 'Abu Dhabi' WHERE id = 'united-arab-emirates';
UPDATE countries SET capital = 'London' WHERE id = 'united-kingdom';
UPDATE countries SET capital = 'Washington, D.C.' WHERE id = 'united-states';
UPDATE countries SET capital = 'Montevideo' WHERE id = 'uruguay';
UPDATE countries SET capital = 'Tashkent' WHERE id = 'uzbekistan';
UPDATE countries SET capital = 'Port Vila' WHERE id = 'vanuatu';
UPDATE countries SET capital = 'Vatican City' WHERE id = 'vatican-city';
UPDATE countries SET capital = 'Caracas' WHERE id = 'venezuela';
UPDATE countries SET capital = 'Hanoi' WHERE id = 'vietnam';
UPDATE countries SET capital = 'Sana''a' WHERE id = 'yemen';
UPDATE countries SET capital = 'Lusaka' WHERE id = 'zambia';
UPDATE countries SET capital = 'Harare' WHERE id = 'zimbabwe';