// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qonnpyaemjpudtptsuyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFvbm5weWFlbWpwdWR0cHRzdXl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDQ2NjIsImV4cCI6MjA2NDUyMDY2Mn0.PK2fovbHLd256rOy6HTgM7qqFRbo7aEdYH97PU5eTxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);